server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

ribbon:
  eureka:
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-cloud?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  redis:
    host: 10.13.98.57
    port: 6379
    pool:
      max-idle: 100
      max-active: 100
      max-wait: 10000


  rabbitmq:
    host: 10.13.98.194:5672
    username: admin
    password: 123456
    publisher-confirms: true
    publisher-returns: true

mybatis:
  mapperLocations: classpath:com/actuator/mapper/xml/**/*Mapper.xml
  typeAliasesPackage: com.actuator.entity.**
  configLocation: classpath:/META-INF/mybatis/mybatis-config.xml
management:
  port: 9001
  security:
    enabled: false


